GET http://localhost:8080/serve_report/2
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzQxNjIyMDEsImlzQWRtaW4iOmZhbHNlLCJsb2dpbiI6InRlc3R1c2VyIiwidXNlcklkIjoxfQ.2CcLlMbidMlzXYLYGgclrtDZ4lmr4CAsqZWo8zwxNfg
isAdmin : false